CREATE TABLE POSTAL_CODE
(
    ID    SERIAL PRIMARY KEY,
    CODE  VARCHAR(4)  NOT NULL,
    LABEL VARCHAR(85) NOT NULL
);

CREATE TABLE ADDRESS
(
    ID             SERIAL PRIMARY KEY,
    STREET_NAME    VARCHAR(32) NOT NULL,
    STREET_NUMBER  VARCHAR(10) NOT NULL,
    FK_POSTAL_CODE integer     NOT NULL,
    CONSTRAINT FK_ADDRESS_POSTAL_CODE foreign key (FK_POSTAL_CODE) references POSTAL_CODE (ID)
);

CREATE TABLE EMAIL_ADDRESS
(
    ID       SERIAL PRIMARY KEY,
    USERNAME VARCHAR(64) NOT NULL,
    DOMAIN   VARCHAR(64) NOT NULL
);

CREATE TABLE PHONE_NUMBER
(
    ID     SERIAL PRIMARY KEY,
    PREFIX VARCHAR(4)  NOT NULL,
    NUMBER VARCHAR(20) NOT NULL
);

CREATE TABLE PERSON
(
    ID               SERIAL PRIMARY KEY,
    NAME             VARCHAR(64) NOT NULL,
    FK_PHONE_NUMBER  integer,
    FK_MOBILE_NUMBER integer,
    FK_EMAIL_ADDRESS integer     NOT NULL,
    FK_ADDRESS       integer     NOT NULL,
    role             VARCHAR(20),
    CONSTRAINT FK_PERSON_PHONE_NUMBER foreign key (FK_PHONE_NUMBER) references PHONE_NUMBER (ID),
    CONSTRAINT FK_PERSON_MOBILE_NUMBER foreign key (FK_MOBILE_NUMBER) references PHONE_NUMBER (ID),
    CONSTRAINT FK_PERSON_EMAIL_ADDRESS foreign key (FK_EMAIL_ADDRESS) references EMAIL_ADDRESS (ID),
    CONSTRAINT FK_PERSON_ADDRESS foreign key (FK_ADDRESS) references ADDRESS (ID)
);