
CREATE TABLE POSTALCODE
    (
        ID SERIAL PRIMARY KEY,
        CODE VARCHAR(4) NOT NULL,
        LABEL VARCHAR(85) NOT NULL
);

CREATE TABLE ADDRESS
(
    ID SERIAL PRIMARY KEY,
    STREETNAME VARCHAR(32) NOT NULL,
    STREETNUMBER VARCHAR(10) NOT NULL,
    FK_POSTALCODE integer NOT NULL,
    CONSTRAINT FK_ADDRESS_POSTALCODE foreign key (FK_POSTALCODE) references POSTALCODE (ID)
);

CREATE TABLE EMAILADDRESS
(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(64) NOT NULL,
    DOMAIN VARCHAR(64) NOT NULL
);

CREATE TABLE PHONENUMBER
(
    ID SERIAL PRIMARY KEY,
    PREFIX VARCHAR(4) NOT NULL,
    NUMBER VARCHAR(20) NOT NULL
);

CREATE TABLE CONTACTPERSON
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    FK_PHONENUMBER integer ,
    FK_MOBILENUMBER integer ,
    FK_EMAILADDRESS integer NOT NULL,
    FK_ADDRESS integer NOT NULL,
    CONSTRAINT FK_CONTACTPERSON_PHONENUMBER foreign key (FK_PHONENUMBER) references PHONENUMBER(ID),
    CONSTRAINT FK_CONTACTPERSON_MOBILENUMBER foreign key (FK_MOBILENUMBER) references PHONENUMBER(ID),
    CONSTRAINT FK_CONTACTPERSON_EMAILADDRESS foreign key (FK_EMAILADDRESS) references EMAILADDRESS(ID),
    CONSTRAINT FK_CONTACTPERSON_ADDRESS foreign key (FK_ADDRESS) references ADDRESS(ID)
);
