
CREATE TABLE PERSON
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    FK_PHONENUMBER integer ,
    FK_MOBILENUMBER integer ,
    FK_EMAILADDRESS integer NOT NULL,
    FK_ADDRESS integer NOT NULL,
    CONSTRAINT FK_PERSON_PHONENUMBER foreign key (FK_PHONENUMBER) references PHONENUMBER(ID),
    CONSTRAINT FK_PERSON_MOBILENUMBER foreign key (FK_MOBILENUMBER) references PHONENUMBER(ID),
    CONSTRAINT FK_PERSON_EMAILADDRESS foreign key (FK_EMAILADDRESS) references EMAILADDRESS(ID),
    CONSTRAINT FK_PERSON_ADDRESS foreign key (FK_ADDRESS) references ADDRESS(ID)
);

DROP TABLE CONTACTPERSON CASCADE;
